### ISSUE TITLE
Support impersonation in dev mode

### ISSUE THREAD

**Issue by davhdavh** [Catglobe/Catglobe.CgScript#8]

**Comment by davhdavh** [comment]
@nguyenthiduyan 
This adds `Workflow_getGlobal` and `Workflow_setGlobal`. You can use these to set values that are available in ALL scripts invoked from workflow class.

Also added WorkflowScript.DynamicScriptName, which is used in error reporting if set.

**Comment by nguyenthiduyan** [comment]
Added wiki page for [Workflow_getGlobal](https://wiki.catglobe.com/Workflow_getGlobal) and [Workflow_setGlobal](https://wiki.catglobe.com/Workflow_setGlobal) functions. 
Updated wiki page of [WorkflowScript class](https://wiki.catglobe.com/WorkflowScript_class) to add new property **DynamicScriptName**
